import { PantoneStyle } from './types';

export const PANTONE_STYLES: PantoneStyle[] = [
  { id: 'classic-blue', name: 'Classic Blue', code: '19-4052', primary: '#00467F', secondary: '#E5EBF1', accent: '#FFD700', background: '#F8FAFC', text: '#0F172A', card: '#FFFFFF', border: '#E2E8F0' },
  { id: 'viva-magenta', name: 'Viva Magenta', code: '18-1750', primary: '#BB2649', secondary: '#FCE7EB', accent: '#FFD700', background: '#FDF2F4', text: '#1A050A', card: '#FFFFFF', border: '#F4D0D8' },
  { id: 'illuminating', name: 'Illuminating', code: '13-0647', primary: '#F5DF4D', secondary: '#939597', accent: '#000000', background: '#F8F9FA', text: '#212529', card: '#FFFFFF', border: '#DEE2E6' },
  { id: 'very-peri', name: 'Very Peri', code: '17-3938', primary: '#6667AB', secondary: '#E8E8F3', accent: '#FFD700', background: '#F5F5FA', text: '#1A1A2E', card: '#FFFFFF', border: '#D1D1E9' },
  { id: 'living-coral', name: 'Living Coral', code: '16-1546', primary: '#FF6F61', secondary: '#FFEBE9', accent: '#00467F', background: '#FFF5F4', text: '#2D1412', card: '#FFFFFF', border: '#FFD6D2' },
  { id: 'ultra-violet', name: 'Ultra Violet', code: '18-3838', primary: '#5F4B8B', secondary: '#E9E6F1', accent: '#FFD700', background: '#F4F2F8', text: '#1A1426', card: '#FFFFFF', border: '#D3CDE3' },
  { id: 'greenery', name: 'Greenery', code: '15-0343', primary: '#88B04B', secondary: '#F0F5E9', accent: '#00467F', background: '#F7FAF4', text: '#1B240F', card: '#FFFFFF', border: '#E1EDD3' },
  { id: 'rose-quartz', name: 'Rose Quartz', code: '13-1520', primary: '#F7CAC9', secondary: '#92A8D1', accent: '#FFFFFF', background: '#FDF8F8', text: '#2D2525', card: '#FFFFFF', border: '#F1DEDD' },
  { id: 'marsala', name: 'Marsala', code: '18-1438', primary: '#955251', secondary: '#EFE6E6', accent: '#FFD700', background: '#F7F2F2', text: '#261515', card: '#FFFFFF', border: '#DFCDCC' },
  { id: 'radiant-orchid', name: 'Radiant Orchid', code: '18-3224', primary: '#B163A3', secondary: '#F4EAF3', accent: '#FFD700', background: '#F9F4F8', text: '#261523', card: '#FFFFFF', border: '#E9D5E6' },
];

export const TRANSLATIONS = {
  en: {
    dashboard: 'WOW Control Center',
    mdri: 'MDRI Pipeline',
    studio: 'Agent Studio',
    settings: 'Settings',
    activeJobs: 'Active Jobs',
    tokenUsage: 'Token Usage',
    avgLatency: 'Avg Latency',
    providerHealth: 'Provider Health',
    liveLog: 'Live Log Terminal',
    inputPanel: 'Input Panel',
    agentProgress: 'Agent Chain Progress',
    artifactViewer: 'Artifact Viewer',
    promptEditor: 'Prompt Editor',
    modelSelector: 'Model Selector',
    theme: 'Theme',
    language: 'Language',
    stylePalette: 'Style Palette',
    jackslot: 'Jackslot Reset',
    light: 'Light',
    dark: 'Dark',
    english: 'English',
    chinese: 'Traditional Chinese',
    step1: 'Web Research',
    step2: 'Report Generation',
    step3: 'Skill Creation',
    generate: 'Start Pipeline',
    approve: 'Approve & Next',
    edit: 'Edit Artifact',
    save: 'Save Changes',
    cancel: 'Cancel',
    placeholder: 'Paste raw regulation text here...',
    templatePlaceholder: 'Paste report template here...',
    additionalFeatures: 'AI Intelligence Features',
    riskScore: 'Regulatory Risk Score',
    gapAnalysis: 'Gap Analysis',
    checklist: 'Auto-Checklist',
  },
  zh: {
    dashboard: 'WOW 控制中心',
    mdri: 'MDRI 流程',
    studio: '智能體工作室',
    settings: '設定',
    activeJobs: '進行中任務',
    tokenUsage: 'Token 使用量',
    avgLatency: '平均延遲',
    providerHealth: '服務狀態',
    liveLog: '實時日誌終端',
    inputPanel: '輸入面板',
    agentProgress: '智能體鏈進度',
    artifactViewer: '產出查看器',
    promptEditor: '提示詞編輯器',
    modelSelector: '模型選擇',
    theme: '主題',
    language: '語言',
    stylePalette: '風格調色盤',
    jackslot: 'Jackslot 重置',
    light: '淺色',
    dark: '深色',
    english: '英文',
    chinese: '繁體中文',
    step1: '網路研究',
    step2: '報告生成',
    step3: '技能創建',
    generate: '啟動流程',
    approve: '批准並下一步',
    edit: '編輯產出',
    save: '保存更改',
    cancel: '取消',
    placeholder: '在此貼上原始法規文本...',
    templatePlaceholder: '在此貼上報告模板...',
    additionalFeatures: 'AI 智能功能',
    riskScore: '法規風險評分',
    gapAnalysis: '差異分析',
    checklist: '自動清單',
  }
};
